### ISSUE TITLE
Error showing content - non-standard json content-type.

### ISSUE THREAD

**Issue by cschneid** [jkbrzt/httpie#344]
Running into an error:

```
› http http://aa/directory/
HTTP/1.1 200 OK
Cache-Control: max-age=300, public
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/vnd.comverge.grid+hal+json; charset=utf-8
Date: Mon, 27 Apr 2015 18:05:43 GMT
Server: nginx/1.6.2 + Phusion Passenger 4.0.59
Status: 200 OK
Transfer-Encoding: chunked
Vary: Authorization,Accept,Prefer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Phusion Passenger 4.0.59
X-Request-Id: 4d321725-bb49-4347-bba4-9b55a781c0bd
X-Runtime: 0.541456
X-XSS-Protection: 1; mode=block


http: error: ValueError: too many values to unpack
```

The actual value is json, just with an application specific content type:

Example (heavily minimized).
```
{"_links":{"self":{"href":"http://aa/directory/directory"}}}
```

**Comment by jakubroztocil** [comment]
@cschneid would you please invoke the same command but with `--debug --traceback`?

**Comment by cschneid** [comment]
```
› http --debug --traceback http://aa/directory/
HTTPie 0.9.2
HTTPie data: /Users/cschneid/.httpie
Requests 2.6.0
Pygments 2.0.2
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] darwin

>>> requests.request({'allow_redirects': False,
 'auth': None,
 'cert': None,
 'data': OrderedDict(),
 'files': DataDict(),
 'headers': {'User-Agent': 'HTTPie/0.9.2'},
 'method': 'get',
 'params': ParamsDict(),
 'proxies': {},
 'stream': True,
 'timeout': 30,
 'url': u'http://aa/directory/',
 'verify': True})

HTTP/1.1 200 OK
Cache-Control: max-age=300, public
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/vnd.comverge.grid+hal+json; charset=utf-8
Date: Mon, 27 Apr 2015 18:17:44 GMT
Server: nginx/1.6.2 + Phusion Passenger 4.0.59
Status: 200 OK
Transfer-Encoding: chunked
Vary: Authorization,Accept,Prefer
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: Phusion Passenger 4.0.59
X-Request-Id: 2b2bbe80-e0ca-4a63-8e1c-59d6e57b07f7
X-Runtime: 0.041420
X-XSS-Protection: 1; mode=block

Traceback (most recent call last):
  File "/usr/local/Cellar/httpie/0.9.2_1/libexec/bin/http", line 9, in <module>
    load_entry_point('httpie==0.9.2', 'console_scripts', 'http')()
  File "/usr/local/Cellar/httpie/0.9.2_1/libexec/lib/python2.7/site-packages/httpie/core.py", line 142, in main
    write(**write_kwargs)
  File "/usr/local/Cellar/httpie/0.9.2_1/libexec/lib/python2.7/site-packages/httpie/output/streams.py", line 35, in write
    for chunk in stream:
  File "/usr/local/Cellar/httpie/0.9.2_1/libexec/lib/python2.7/site-packages/httpie/output/streams.py", line 157, in __iter__
    for chunk in self.iter_body():
  File "/usr/local/Cellar/httpie/0.9.2_1/libexec/lib/python2.7/site-packages/httpie/output/streams.py", line 293, in iter_body
    yield self.process_body(body)
  File "/usr/local/Cellar/httpie/0.9.2_1/libexec/lib/python2.7/site-packages/httpie/output/streams.py", line 263, in process_body
    chunk = self.formatting.format_body(content=chunk, mime=self.mime)
  File "/usr/local/Cellar/httpie/0.9.2_1/libexec/lib/python2.7/site-packages/httpie/output/processing.py", line 49, in format_body
    content = p.format_body(content, mime)
  File "/usr/local/Cellar/httpie/0.9.2_1/libexec/lib/python2.7/site-packages/httpie/output/formatters/colors.py", line 54, in format_body
    lexer = self.get_lexer(mime)
  File "/usr/local/Cellar/httpie/0.9.2_1/libexec/lib/python2.7/site-packages/httpie/output/formatters/colors.py", line 62, in get_lexer
    self.lexer_cache[mime] = get_lexer(mime)
  File "/usr/local/Cellar/httpie/0.9.2_1/libexec/lib/python2.7/site-packages/httpie/output/formatters/colors.py", line 72, in get_lexer
    subtype_name, subtype_suffix = subtype.split('+')
ValueError: too many values to unpack
```

**Comment by jakubroztocil** [comment]
Thanks. HTTPie doesn't expect multiple `+subtype` occurrences. I don't think it's valid to have multiple subtypes, but HTTPie shouldn't throw an error nevertheless.

```http
Content-Type: application/vnd.comverge.grid+hal+json; charset=utf-8
```

**Comment by cschneid** [comment]
From my reading of https://tools.ietf.org/html/rfc2045#section-5 - it seems like `+` isn't a special character.  We have a single subtype that starts with `vnd` and happens to have plusses in it?  Not that I'm any good at reading RFCs...

```
     token := 1*<any (US-ASCII) CHAR except SPACE, CTLs,
                 or tspecials>

     tspecials :=  "(" / ")" / "<" / ">" / "@" /
                   "," / ";" / ":" / "\" / <">
                   "/" / "[" / "]" / "?" / "="
                   ; Must be in quoted-string,
                   ; to use within parameter values
```
