### ISSUE TITLE
ImportError: No module named _curses

### ISSUE THREAD

**Issue by bixu** [jkbrzt/httpie#366]
```
pkgin install py27-pip-1.5.6

pip install --upgrade pip setuptools
Downloading/unpacking pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-7.1.0-py2.py3-none-any.whl#md5=b108384a762825ec20345bb9b5b7209f
  Downloading pip-7.1.0-py2.py3-none-any.whl (1.1MB): 1.1MB downloaded
Downloading/unpacking setuptools from https://pypi.python.org/packages/3.4/s/setuptools/setuptools-18.0.1-py2.py3-none-any.whl#md5=19c0c145c3d2a615b0a33f0aeddd1c02
  Downloading setuptools-18.0.1-py2.py3-none-any.whl (461kB): 461kB downloaded
Installing collected packages: pip, setuptools
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
  Found existing installation: setuptools 14.2
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed pip setuptools
Cleaning up...

pip install --upgrade httpie
Collecting httpie
  Downloading httpie-0.9.2-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 69kB 646kB/s
Collecting requests>=2.3.0 (from httpie)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |████████████████████████████████| 471kB 831kB/s
Collecting Pygments>=1.5 (from httpie)
  Downloading Pygments-2.0.2-py2-none-any.whl (672kB)
    100% |████████████████████████████████| 675kB 661kB/s
Installing collected packages: requests, Pygments, httpie
Successfully installed Pygments-2.0.2 httpie-0.9.2 requests-2.7.0

http google.com
Traceback (most recent call last):
  File "/usr/pkg/bin/http", line 7, in <module>
    from httpie.__main__ import main
  File "/usr/pkg/lib/python2.7/site-packages/httpie/__main__.py", line 6, in <module>
    from .core import main
  File "/usr/pkg/lib/python2.7/site-packages/httpie/core.py", line 23, in <module>
    from httpie.downloads import Download
  File "/usr/pkg/lib/python2.7/site-packages/httpie/downloads.py", line 15, in <module>
    from httpie.output.streams import RawStream
  File "/usr/pkg/lib/python2.7/site-packages/httpie/output/streams.py", line 5, in <module>
    from httpie.context import Environment
  File "/usr/pkg/lib/python2.7/site-packages/httpie/context.py", line 7, in <module>
    class Environment(object):
  File "/usr/pkg/lib/python2.7/site-packages/httpie/context.py", line 29, in Environment
    import curses
  File "/usr/pkg/lib/python2.7/curses/__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses
```

**Comment by surindergithub** [comment]
I didn't faced any error while installing and upgrading httpie with python2.7.

**Comment by rghv** [comment]
Seconded. This is reproducible.

```
10:59:55 ~ 
 $ pyenv global 
2.7.6
11:00:41 ~ 
 $ type pip
pip is /edge/tools/pyenv/root/shims/pip
11:00:45 ~ 
 $ pip install httpie --upgrade
Collecting httpie
/edge/tools/pyenv/root/versions/2.7.6/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading httpie-0.9.2-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 69kB 155kB/s 
Collecting requests>=2.3.0 (from httpie)
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
    100% |████████████████████████████████| 471kB 967kB/s 
Collecting Pygments>=1.5 (from httpie)
  Downloading Pygments-2.0.2-py2-none-any.whl (672kB)
    100% |████████████████████████████████| 675kB 474kB/s 
Installing collected packages: requests, Pygments, httpie
Successfully installed Pygments-2.0.2 httpie-0.9.2 requests-2.7.0
11:01:02 ~ 
 $ http GET github.com
Traceback (most recent call last):
  File "/edge/tools/pyenv/root/versions/2.7.6/bin/http", line 7, in <module>
    from httpie.__main__ import main
  File "/edge/tools/pyenv/root/versions/2.7.6/lib/python2.7/site-packages/httpie/__main__.py", line 6, in <module>
    from .core import main
  File "/edge/tools/pyenv/root/versions/2.7.6/lib/python2.7/site-packages/httpie/core.py", line 23, in <module>
    from httpie.downloads import Download
  File "/edge/tools/pyenv/root/versions/2.7.6/lib/python2.7/site-packages/httpie/downloads.py", line 15, in <module>
    from httpie.output.streams import RawStream
  File "/edge/tools/pyenv/root/versions/2.7.6/lib/python2.7/site-packages/httpie/output/streams.py", line 5, in <module>
    from httpie.context import Environment
  File "/edge/tools/pyenv/root/versions/2.7.6/lib/python2.7/site-packages/httpie/context.py", line 7, in <module>
    class Environment(object):
  File "/edge/tools/pyenv/root/versions/2.7.6/lib/python2.7/site-packages/httpie/context.py", line 29, in Environment
    import curses
  File "/edge/tools/pyenv/root/versions/2.7.6/lib/python2.7/curses/__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses
11:01:11 ~ 
```

A search points to [this SO thread about UniCurses](http://stackoverflow.com/questions/17410116/error-no-module-named-curses). But pip doesn't seem to locate/get unicurses. [Unicurses](https://github.com/Chiel92/unicurses) doesn't look like a python module, if that's indeed the true source. (Though it is [mentioned on pypi](https://pypi.python.org/pypi/UniCurses/1.2))

Any other python module that once could use to get the curses functionality? `pip search curses` shows pyCDK but pip fails to install pyCDK as well.

**Comment by gak** [comment]
For my system (Arch Linux), I found that it was looking for the previous version of cursesw:

```
> python
Python 3.5.0 (default, Sep 24 2015, 15:17:54) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from _curses import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libncursesw.so.5: cannot open shared object file: No such file or directory
```

The fix for me was to reinstall Python (I did this via `pyenv install 3.5.0`). Before this I also updated pyenv (via `git pull`), but I am not sure if this step is part of the solution.

```
> pyenv install 3.5.0
pyenv: /home/gak/.pyenv/versions/3.5.0 already exists
continue with installation? (y/N) y
Installing Python-3.5.0...
Installed Python-3.5.0 to /home/gak/.pyenv/versions/3.5.0
```

Then it works again:

```
> python
Python 3.5.0 (default, Nov  5 2015, 09:31:06) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from _curses import *
>>>
```

My guess is Python is somehow linked to curses, even though I can't see any reference to it with `ldd`:

```
ldd /home/gak/.pyenv/versions/3.5.0/bin/python
	linux-vdso.so.1 (0x00007ffc8ad7c000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f2fc79a4000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f2fc77a0000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f2fc759d000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f2fc729f000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f2fc6efb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2fc7bc1000)
```

**Comment by jkbrzt** [comment]
Thanks @gak!

**Comment by jamshid** [comment]
In my case httpie was reporting `ImportError: No module named _curses` because I was trying to run it with a custom `python2.7` install on a CentOS6 machine. I had to `pip uninstall httpie` then `pip2.6 install httpie` to get it working.
