### ISSUE TITLE
ImportError: No module named packages

### ISSUE THREAD

**Issue by rombert** [jkbrzt/httpie#400]
After a recent system update httpie no longer works. I suspect that requests going from 2.7.0 to 2.8.0 was the trigger

$ rpm -q python-requests 
python-requests-2.8.0-1.1.noarch

Traceback (most recent call last):
  File "/usr/bin/http", line 9, in <module>
    load_entry_point('httpie==0.9.2', 'console_scripts', 'http')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/httpie/__main__.py", line 6, in <module>
    from .core import main
  File "/usr/lib/python2.7/site-packages/httpie/core.py", line 22, in <module>
    from httpie.client import get_response
  File "/usr/lib/python2.7/site-packages/httpie/client.py", line 6, in <module>
    from requests.packages import urllib3
ImportError: No module named packages

**Comment by sigmavirus24** [comment]
This is due to your system packager deliberately breaking requests' API. Requests 2.8.0 did not break this
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rombert** [comment]
A package update fixed this. Sorry for the noise
