### ISSUE TITLE
pkg_resources.DistributionNotFound: Pygments>=1.5

### ISSUE THREAD

**Issue by kamal2222ahmed** [jkbrzt/httpie#406]
$ http httpie.org
Traceback (most recent call last):
  File "/usr/bin/http", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Pygments>=1.5

here is the install stdout:

sudo pip install --upgrade https://github.com/jkbrzt/httpie/tarball/master
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting https://github.com/jkbrzt/httpie/tarball/master
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://github.com/jkbrzt/httpie/tarball/master
     | 258kB 4.2MB/s
Collecting requests>=2.3.0 (from httpie==1.0.0-dev)
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading requests-2.8.1-py2.py3-none-any.whl (497kB)
    100% |████████████████████████████████| 499kB 872kB/s
Collecting Pygments>=1.5 (from httpie==1.0.0-dev)
  Downloading Pygments-2.0.2-py2-none-any.whl (672kB)
    100% |████████████████████████████████| 675kB 593kB/s
Collecting argparse>=1.2.1 (from httpie==1.0.0-dev)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Installing collected packages: requests, Pygments, argparse, httpie
  Running setup.py install for httpie
Successfully installed Pygments-2.0.2 argparse-1.4.0 httpie-1.0.0.dev0 requests-2.8.1

env:
uname -a
Linux hostname.network  2.6.32-358.14.1.el6.x86_64

cat /etc/centos-release
CentOS release 6.4 (Final)

python --version
Python 2.6.6

**Comment by kamal2222ahmed** [comment]
resolve it by using easy_install:

sudo easy_install httpie
Searching for httpie
Best match: httpie 0.8.0
Adding httpie 0.8.0 to easy-install.pth file
Installing http script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Processing dependencies for httpie
Finished processing dependencies for httpie
kahmed@mars:~$ which http
/usr/local/bin/http
kahmed@mars:~$ http google.com
HTTP/1.1 301 Moved Permanently
Cache-Control: public, max-age=2592000
Content-Length: 219
Content-Type: text/html; charset=UTF-8
Date: Sat, 31 Oct 2015 04:06:07 GMT
Expires: Mon, 30 Nov 2015 04:06:07 GMT
Location: http://www.google.com/
Server: gws
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
