### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode' on --download

### ISSUE THREAD

**Issue by Hubbitus** [jkbrzt/httpie#412]
http --debug --session=test --timeout 10000 --check-status --download 'http://37.143.19.22:8443/portal-api/rest/bo/plants-sale-contracts?_dc=1447383987687&return_count=no&page=1&s.....'

```
HTTPie 0.9.2
HTTPie data: /home/pasha/.httpie
Requests 2.7.0
Pygments 1.6
Python 2.7.10 (default, Sep  8 2015, 17:20:17)
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] linux2

>>> requests.request({'allow_redirects': True,
 'auth': None,
 'cert': None,
 'data': OrderedDict(),
 'files': DataDict(),
 'headers': {u'Accept': 'application/json',
             'Accept-Encoding': None,
             'User-Agent': 'HTTPie/0.9.2',
             u'password': 'admin',
             u'user': 'admin'},
 'method': 'get',
 'params': ParamsDict(),
 'proxies': {},
 'stream': True,
 'timeout': 10000.0,
 'url': u'http://37.143.19.22:8443/portal-api/rest/bo/plants-sale-contracts?_dc=1447383987687&return_count=no&page=1&start=0&size=20&sort=%5B%7B%22property%22%3A%22party%22%2C%22direction%22%3A%22ASC%22%7D%5D&filter=%5B%7B%22property%22%3A%22sourceSystem%22%2C%22value%22%3A%22%22%2C%22operator%22%3A%22%3D%22%7D%5D',
 'verify': True})

Traceback (most recent call last):
  File "/bin/http", line 9, in <module>
    load_entry_point('httpie==0.9.2', 'console_scripts', 'http')()
  File "/usr/lib/python2.7/site-packages/httpie/core.py", line 112, in main
    response = get_response(args, config_dir=env.config.directory)
  File "/usr/lib/python2.7/site-packages/httpie/client.py", line 48, in get_response
    read_only=bool(args.session_read_only),
  File "/usr/lib/python2.7/site-packages/httpie/sessions.py", line 52, in get_response
    session.update_headers(kwargs['headers'])
  File "/usr/lib/python2.7/site-packages/httpie/sessions.py", line 104, in update_headers
    value = value.decode('utf8')
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by sigmavirus24** [comment]
Is your `test` session working with any other request? It looks like this is related to the use of you `--session=test`.

**Comment by Hubbitus** [comment]
It work if I remove --download option. It was used as workaround to find way print headers and body on sstdout and stderr separately.

**Comment by Hubbitus** [comment]
Thank you.

**Comment by Hubbitus** [comment]
Do you plan make new version release with it? Or it already contained in one?

**Comment by jkbrzt** [comment]
Still to be released — hopefully soon!
