### ISSUE TITLE
Command shouldn't die if urllib3 doesn't define "disable_warnings" method

### ISSUE THREAD

**Issue by hangtwenty** [jkbrzt/httpie#418]
I've happily used `httpie` for a while now. Now, I'm trying to get my team to standardize on `httpie` instead of `curl`. (Aside from being annoying, `curl` interfaces vary across platforms. Better to have a tool that's the same everywhere.)

A teammate -- who uses Windows + cygwin -- is getting a stubborn error, `AttributeError: module 'requests.packages.urllib3' has no attribute 'disable_warnings'`. On both Python 2.7.10 and Python 3.5.0. After trying `pip install --upgrade pip setuptools` and `pip install --upgrade httpie requests`. Nothing seems to fix it.

Python 2.7.10:
```
File "C:\python2710\lib\runpy.py", line 162, in _run_module_as_main
   "__main__", fname, loader, pkg_name)
 File "C:\python2710\lib\runpy.py", line 72, in _run_code
   exec code in run_globals
 File "C:\Python2710\Scripts\http.exe\__main__.py", line 5, in <module>
 File "C:\python2710\lib\site-packages\httpie\__main__.py", line 6, in <module>
   from .core import main
 File "C:\python2710\lib\site-packages\httpie\core.py", line 22, in <module>
   from httpie.client import get_response
 File "C:\python2710\lib\site-packages\httpie\client.py", line 15, in <module>
   urllib3.disable_warnings()
```

Python 3.5.0:

```
Traceback (most recent call last):
 File "C:\Users\redacted\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 170, in _run_module_as_main
   "__main__", mod_spec)
 File "C:\Users\redacted\AppData\Local\Programs\Python\Python35-32\lib\runpy.py", line 85, in _run_code
   exec(code, run_globals)
 File "C:\Users\redacted\AppData\Local\Programs\Python\Python35-32\lib\site-packages\httpie\__main__.py", line 6, in <module>
   from .core import main
 File "C:\Users\redacted\AppData\Local\Programs\Python\Python35-32\lib\site-packages\httpie\core.py", line 22, in <module>
   from httpie.client import get_response
 File "C:\Users\redacted\AppData\Local\Programs\Python\Python35-32\lib\site-packages\httpie\client.py", line 15, in <module>
   urllib3.disable_warnings()
```

Looking into [the urllib3 security docs](https://urllib3.readthedocs.org/en/latest/security.html) ... we should fail gracefully here and move on. All that will happen is some logging noise. This may inconvenience users with this edge case ... but better that they can actually use httpie!

**Comment by hangtwenty** [comment]
Note that another way this could be addressed is by using environment variables. If a user has this edge case and REALLY STILL doesn't want the warnings, they can address it themselves. [From the docs](https://github.com/hangtwenty/httpie.git)

```bash
PYTHONWARNINGS="ignore:Unverified HTTPS request"
```

They can just set that variable, either permanently in an shell rc file, or ad-hoc. We can even mention this in the httpie docs ... but I would think such a user could Google their traceback, find this ticket, and learn what to do :stuck_out_tongue:

**Comment by jkbrzt** [comment]
Merged, will be released soon
