### ISSUE TITLE
ssl errors

### ISSUE THREAD

**Issue by nhooyr** [jkbrzt/httpie#454]
This is my command:

```
[$] http --verify=no https://localhost:443

http: error: SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590) while doing GET request to URL: https://localhost:443/
```

I think this error is because the certificate is self signed, but I have verify turned off.

version is latest master on OSX. 

works fine with curl

```
[$] curl -k https://localhost:443
```

**Comment by jkbrzt** [comment]
https://github.com/jkbrzt/httpie/blob/master/CONTRIBUTING.rst#1-reporting-bugs

**Comment by nhooyr** [comment]
```

HTTPie 1.0.0-dev
Requests 2.9.1
Pygments 2.0.2
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
/usr/bin/python
Darwin 15.4.0

<Environment {
    "colors": 256,
    "config": {
        "__meta__": {
            "about": "u'HTTPie configuration file'",
            "help": "u'https://github.com/jkbrzt/httpie#config'",
            "httpie": "u'1.0.0-dev'"
        },
        "default_options": "[u'--style=bw']"
    },
    "config_dir": "/Users/nhooyr/.httpie",
    "is_windows": false,
    "stderr": "<open file '<stderr>', mode 'w' at 0x102c851e0>",
    "stderr_isatty": true,
    "stdin": "<open file '<stdin>', mode 'r' at 0x102c850c0>",
    "stdin_encoding": "UTF-8",
    "stdin_isatty": true,
    "stdout": "<open file '<stdout>', mode 'w' at 0x102c85150>",
    "stdout_encoding": "UTF-8",
    "stdout_isatty": true
}>

>>> requests.request(**{
    "allow_redirects": false,
    "auth": "None",
    "cert": "None",
    "data": {},
    "files": {},
    "headers": {
        "User-Agent": "HTTPie/1.0.0-dev"
    },
    "method": "get",
    "params": {},
    "proxies": {},
    "stream": true,
    "timeout": 30,
    "url": "u'https://localhost:443'",
    "verify": false
})


http: error: SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590) while doing GET request to URL: https://localhost:443/
Traceback (most recent call last):
  File "/usr/local/Cellar/httpie/HEAD/libexec/bin/http", line 9, in <module>
    load_entry_point('httpie==1.0.0.dev0', 'console_scripts', 'http')()
  File "/usr/local/Cellar/httpie/HEAD/libexec/lib/python2.7/site-packages/httpie/core.py", line 227, in main
    log_error=log_error,
  File "/usr/local/Cellar/httpie/HEAD/libexec/lib/python2.7/site-packages/httpie/core.py", line 99, in program
    final_response = get_response(args, config_dir=env.config.directory)
  File "/usr/local/Cellar/httpie/HEAD/libexec/lib/python2.7/site-packages/httpie/client.py", line 70, in get_response
    response = requests_session.request(**kwargs)
  File "/usr/local/Cellar/httpie/HEAD/libexec/vendor/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/Cellar/httpie/HEAD/libexec/vendor/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/Cellar/httpie/HEAD/libexec/vendor/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
r
```

**Comment by nhooyr** [comment]
It also seems as though I can put anything in `--verify=` without an error?

And for some reason, `httpie` is using the old version of ssl on OSX. The best protocol I get for `--ssl=` is `tis1`. In python if I do, `import ssl` and then `ssl.OPENSSL_VERSION`, I get the new one.

**Comment by jkbrzt** [comment]
How was httpie installed?

**Comment by nhooyr** [comment]
@jkbrzt `brew install httpie --HEAD` was the problem

Installing it as `pip install --upgrade https://github.com/jkbrzt/httpie/archive/master.tar.gz` fixes my problem.
