### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Johnybe** [jkbrzt/httpie#478]
Hello,

httpie installed on debian 8 : 

http httpie.org                                                                                                                                                    
Traceback (most recent call last):
  File "/usr/bin/http", line 9, in <module>
    load_entry_point('httpie==0.8.0', 'console_scripts', 'http')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/httpie/__main__.py", line 6, in <module>
    from .core import main
  File "/usr/lib/python2.7/dist-packages/httpie/core.py", line 21, in <module>
    from .compat import str, is_py3
  File "/usr/lib/python2.7/dist-packages/httpie/compat.py", line 6, in <module>
    from requests.compat import (
ImportError: cannot import name is_windows

Thank you for help

**Comment by Johnybe** [comment]
Hello,
It seems a python package conflict

Wich python version we have to install ?

Thank you

**Comment by kinow** [comment]
@Johnybe maybe related to https://github.com/jkbrzt/httpie/issues/314?

**Comment by Johnybe** [comment]
Hello,

Thank you kinow, i removed httpie via apt and upgrade/install via pip : 

sudo apt-get remove httpie
pip install --upgrade pip
sudo pip install httpie
