### ISSUE TITLE
yum install fails on Amazon Linux

### ISSUE THREAD

**Issue by sethrosetter** [jkbrzt/httpie#486]
Using Amazon Linux AMI release 2016.03

```
 [root@XXXX]# yum install httpie
Loaded plugins: priorities, update-motd, upgrade-helper
951 packages excluded due to repository priority protections
No package httpie available.
Error: Nothing to do
```

Am I missing something?

**Comment by jkbrzt** [comment]
I think you might need to add the EPEL repo or something like that. AFAIK the default AL repositories are very limited.

**Comment by cmoulliard** [comment]
In which EPEL repo can we find `httpie` tool ?

**Comment by cmosguy** [comment]
Hello @cmoulliard  I tried to do the 
```
sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
```

However, after I installed it I get:

```
[ec2-user@ip-10-10-10-149 ~]$ http --version
Traceback (most recent call last):
  File "/usr/bin/http", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/dist-packages/pkg_resources/__init__.py", line 3049, in <module>
    @_call_aside
  File "/usr/lib/python2.6/dist-packages/pkg_resources/__init__.py", line 3033, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.6/dist-packages/pkg_resources/__init__.py", line 3062, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.6/dist-packages/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.6/dist-packages/pkg_resources/__init__.py", line 972, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/dist-packages/pkg_resources/__init__.py", line 858, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'httpie==0.9.4' distribution was not found and is required by the
 application
```

Did you ever get this to work on Amazon Linux?

**Comment by will-sargent-eero** [comment]
```
amazon-linux-extras enable epel
yum install epel-release
yum install httpie
```
