### ISSUE TITLE
config.json does not support HTTP headers

### ISSUE THREAD

**Issue by gmarchand** [jkbrzt/httpie#519]
Hello,

When I try this configuration 
```
{
    "__meta__": {
        "about": "HTTPie configuration file",
        "help": "https://github.com/jkbrzt/httpie#config",
        "httpie": "0.9.6"
    },
    "default_options": [
      "--headers",
      "Pragma: foo"
    ]
}
```

I have got this error 

```
HTTPie 0.9.6
Requests 2.11.0
Pygments 2.1.3
Python 3.5.2 (default, Aug 26 2016, 15:51:45) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
/usr/local/opt/python3/bin/python3.5
Darwin 15.6.0

<Environment {
    "colors": 256,
    "config": {
        "__meta__": {
            "about": "HTTPie configuration file",
            "help": "https://github.com/jkbrzt/httpie#config",
            "httpie": "0.9.6"
        },
        "default_options": "['--headers', 'Pragma: foo']"
    },
    "config_dir": "/Users/gumarchand/.httpie",
    "is_windows": false,
    "stderr": "<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>",
    "stderr_isatty": false,
    "stdin": "<_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>",
    "stdin_encoding": "UTF-8",
    "stdin_isatty": true,
    "stdout": "<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>",
    "stdout_encoding": "UTF-8",
    "stdout_isatty": false
}>
Traceback (most recent call last):
  File "/usr/local/Cellar/httpie/0.9.6/libexec/bin/http", line 9, in <module>
    load_entry_point('httpie==0.9.6', 'console_scripts', 'http')()
  File "/usr/local/Cellar/httpie/0.9.6/libexec/lib/python3.5/site-packages/httpie/core.py", line 210, in main
    parsed_args = parser.parse_args(args=args, env=env)
  File "/usr/local/Cellar/httpie/0.9.6/libexec/lib/python3.5/site-packages/httpie/input.py", line 149, in parse_args
    self._guess_method()
  File "/usr/local/Cellar/httpie/0.9.6/libexec/lib/python3.5/site-packages/httpie/input.py", line 300, in _guess_method
    *SEP_GROUP_ALL_ITEMS).__call__(self.args.url))
  File "/usr/local/Cellar/httpie/0.9.6/libexec/lib/python3.5/site-packages/httpie/input.py", line 533, in __call__
    u'"%s" is not a valid value' % string)
argparse.ArgumentTypeError: "www.google.com" is not a valid value
```

**Comment by jkbrzt** [comment]
@gmarchand It's currently not possible to add request items directly to the config. However, you can refer to a session file that includes the headers you'd like to include:

Session file:

```bash
$ cat ~/httpie-custom-headers.json
```
```json
{
    "headers": {
        "Pragma": "foo"
     }
}
```

Config:

```bash
$ cat ~/.httpie/config.json
```
```json
{
    "default_options": [
      "--session-read-only=~/httpie-custom-headers.json"
    ]
}

```

See https://httpie.org/docs#sessions for more info about sessions.

**Comment by gmarchand** [comment]
Thank you very much @jkbrzt 
I use this feature to print akamai debug headers  and it works very well.
