### ISSUE TITLE
problem in httpie/coreapi ssl library?

### ISSUE THREAD

**Issue by kresimir71** [jkbrzt/httpie#538]
By some testing with httpie I have discovered that httpie and coreapi fail to accept an ssl certificate if it does not come first in the 'pem' file:

```bash
$ http -a root:password123 GET https://www.site2.example.com/users/
hostname 'www.site2.example.com' doesn't match either of 'site1.example.com', 'www.site1.example.com'
```

The browsers and curl work OK as expected.

**Comment by jkbrzt** [comment]
Interesting. If you could provide a minimal test case that would be great. Also please read: https://github.com/jkbrzt/httpie/blob/master/CONTRIBUTING.rst#1-reporting-bugs

**Comment by kresimir71** [comment]
The error does not occur when 'site1' is removed from the list of certificates (or it is put at the end of the list)
```
http --traceback -a root:password123 GET https://www.site2.example.com/users/
Traceback (most recent call last):
  File "/usr/bin/http", line 9, in <module>
    load_entry_point('httpie==0.1.6', 'console_scripts', 'http')()
  File "/usr/lib/python2.7/dist-packages/httpie/__main__.py", line 71, in main
    allow_redirects=args.allow_redirects,
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 40, in request
    return s.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 229, in request
    r.send(prefetch=prefetch)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 631, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'www.site2.example.com' doesn't match either of 'site1.example.com', 'www.site1.example.com'
```

**Comment by jkbrzt** [comment]
@kresimir71 [`--debug`](https://github.com/jkbrzt/httpie/blob/master/CONTRIBUTING.rst#1-reporting-bugs)

**Comment by kresimir71** [comment]
Unfortunately,
No `--debug` in command line options.
I have installed it on Debian 7 with
`apt-get install httpie`
Further info:
```
# http --version
0.1.6
# http -h
usage: http [-h] [--version] [--json | --form] [--traceback]
            [--pretty | --ugly] [--headers | --body] [--style STYLE]
            [--auth AUTH] [--verify VERIFY] [--proxy PROXY]
            [--allow-redirects] [--file PATH] [--timeout TIMEOUT]
            METHOD URL [items [items ...]]

HTTPie - cURL for humans.

positional arguments:
  METHOD                HTTP method to be used for the request (GET, POST,
                        PUT, DELETE, PATCH, ...).
  URL                   Protocol defaults to http:// if the URL does not
                        include it.
  items                 HTTP header (key:value), data field (key=value) or raw
                        JSON field (field:=value).

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --json, -j            Serialize data items as a JSON object and set Content-
                        Type to application/json, if not specified.
  --form, -f            Serialize data items as form values and set Content-
                        Type to application/x-www-form-urlencoded, if not
                        specified.
  --traceback           Print exception traceback should one occur.
  --pretty, -p          If stdout is a terminal, the response is prettified by
                        default (colorized and indented if it is JSON). This
                        flag ensures prettifying even when stdout is
                        redirected.
  --ugly, -u            Do not prettify the response.
  --headers, -t         Print only the response headers.
  --body, -b            Print only the response body.
  --style STYLE, -s STYLE
                        Output coloring style, one of autumn, borland, bw,
                        colorful, default, emacs, friendly, fruity, manni,
                        monokai, murphy, native, pastie, perldoc, rrt,
                        solarized, tango, trac, vim, vs. Defaults to
                        solarized.
  --auth AUTH, -a AUTH  username:password
  --verify VERIFY       Set to "yes" to check the host's SSL certificate. You
                        can also pass the path to a CA_BUNDLE file for private
                        certs. You can also set the REQUESTS_CA_BUNDLE
                        environment variable.
  --proxy PROXY         String mapping protocol to the URL of the proxy (e.g.
                        http:foo.bar:3128).
  --allow-redirects     Set this flag if full redirects are allowed (e.g. re-
                        POST-ing of data at new ``Location``)
  --file PATH           File to multipart upload
  --timeout TIMEOUT     Float describes the timeout of the request (Use
                        socket.setdefaulttimeout() as fallback).
```

**Comment by jkbrzt** [comment]
@kresimir71 whoa, v0.1.6 was release almost fiver years ago. I'd recommend uninstalling the deb package and installing the latest version with `pip`. Closing this issue for now, feel free to reopen if the problem persist on the current version.

**Comment by kresimir71** [comment]
I will shortly reopen it, but just remove it as you please because I do not use these utilities actively. Because `coreapi` reacts with the same error and `curl` works correctly, we can of course conclude that the problem is in some python ssl library... 
```

root@buf1512:~# /usr/local/bin/http --version
0.9.6
root@buf1512:~# /usr/local/bin/http --debug -a root:pass1234 GET https://www.site2.example.com/users/
HTTPie 0.9.6
Requests 2.12.1
Pygments 2.1.3
Python 2.7.3 (default, Mar 13 2014, 11:03:55)
[GCC 4.7.2]
/usr/bin/python
Linux 2.6.32-042stab104.1

<Environment {
    "colors": 8,
    "config": {
        "__meta__": {
            "about": "u'HTTPie configuration file'",
            "help": "u'https://github.com/jkbrzt/httpie#config'",
            "httpie": "u'0.9.6'"
        },
        "default_options": "[]"
    },
    "config_dir": "/root/.httpie",
    "is_windows": false,
    "stderr": "<open file '<stderr>', mode 'w' at 0x7fe41dab8270>",
    "stderr_isatty": true,
    "stdin": "<open file '<stdin>', mode 'r' at 0x7fe41dab8150>",
    "stdin_encoding": "ANSI_X3.4-1968",
    "stdin_isatty": true,
    "stdout": "<open file '<stdout>', mode 'w' at 0x7fe41dab81e0>",
    "stdout_encoding": "ANSI_X3.4-1968",
    "stdout_isatty": true
}>

>>> requests.request(**{
    "allow_redirects": false,
    "auth": "<httpie.plugins.builtin.HTTPBasicAuth object at 0x1ef7750>",
    "cert": "None",
    "data": {},
    "files": {},
    "headers": {
        "User-Agent": "HTTPie/0.9.6"
    },
    "method": "u'get'",
    "params": {},
    "proxies": {},
    "stream": true,
    "timeout": 30,
    "url": "u'https://www.site2.example.com/users/'",
    "verify": true
})


http: error: SSLError: hostname 'www.site2.example.com' doesn't match either of 'site1.example.com', 'www.site1.example.com' while doing GET request to URL: https://www.site2.example.com/users/
Traceback (most recent call last):
  File "/usr/local/bin/http", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/httpie/core.py", line 227, in main
    log_error=log_error,
  File "/usr/local/lib/python2.7/dist-packages/httpie/core.py", line 99, in program
    final_response = get_response(args, config_dir=env.config.directory)
  File "/usr/local/lib/python2.7/dist-packages/httpie/client.py", line 70, in get_response
    response = requests_session.request(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'www.site2.example.com' doesn't match either of 'site1.example.com', 'www.site1.example.com'
```

**Comment by sigmavirus24** [comment]
@kresimir71 the version of Python you're using is incredibly old (2.7.3) there are many vulnerabilities in that version and I would be unsurprised if it was causing problems here. Could you also provide `openssl version` please?

**Comment by kresimir71** [comment]
```
openssl version
OpenSSL 1.0.1e 11 Feb 2013
```

**Comment by ygramoel** [comment]
I am experiencing a very similar problem with newer versions of http (0.8.0) and python (3.4.3) 

Below is the output of http, wget and curl on the same url (cairon.net), as well as the output of `http --version` and `python --version`. Feel free to try it with any other http versions.

```
johan@ygramoel:~\> http https://cairon.net

http: error: SSLError: hostname 'cairon.net' doesn't match 'agenda.sikando.be'
johan@ygramoel:~\> curl https://cairon.net
<html>
<header>
<title>This is title</title>
<link rel="stylesheet" type="text/css" href="site.css">
<link rel='stylesheet' href='fullcalendar.css' />
<script src='lib/jquery.min.js'></script>
<script src='lib/moment.min.js'></script>
<script src='fullcalendar.js'></script>
<script src='locale/nl-be.js'></script>
<script src='site.js'/></script>
</header>

<body>
<p>Hello world</p>
<div id='calendar'></div>
</body>
</html>
johan@ygramoel:~\> wget https://cairon.net
--2017-01-18 10:33:26--  https://cairon.net/
Resolving cairon.net (cairon.net)... 178.238.235.158
Connecting to cairon.net (cairon.net)|178.238.235.158|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 427 [text/html]
Saving to: 'index.html'

100%[======================================>] 427         --.-K/s   in 0s      

2017-01-18 10:33:27 (229 MB/s) - 'index.html' saved [427/427]
johan@ygramoel:~\> http --version
0.8.0

johan@ygramoel:~\> python --version
Python 3.4.3
</body>
</html>
johan@ygramoel:~\> wget https://cairon.net
johan@ygramoel:~\> http --version
0.8.0

johan@ygramoel:~\> python --version
Python 3.4.3
```
