### ISSUE TITLE
AttributeError: 'X509' object has no attribute '_x509'

### ISSUE THREAD

**Issue by joshkehn** [jkbrzt/httpie#550]
Versions:

```
HTTPie 0.9.9
Requests 2.12.4
Pygments 2.1.3
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
```

Traceback:

```
Traceback (most recent call last):
  File "/Users/josh/Library/Python/2.7/bin/http", line 11, in <module>
    sys.exit(main())
  File "/Users/josh/Library/Python/2.7/lib/python/site-packages/httpie/__main__.py", line 11, in main
    sys.exit(main())
  File "/Users/josh/Library/Python/2.7/lib/python/site-packages/httpie/core.py", line 227, in main
    log_error=log_error,
  File "/Users/josh/Library/Python/2.7/lib/python/site-packages/httpie/core.py", line 99, in program
    final_response = get_response(args, config_dir=env.config.directory)
  File "/Users/josh/Library/Python/2.7/lib/python/site-packages/httpie/client.py", line 70, in get_response
    response = requests_session.request(**kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
    cert = self.sock.getpeercert()
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 166, in get_subj_alt_name
    cert = _Certificate(openssl_backend, peer_cert._x509)
AttributeError: 'X509' object has no attribute '_x509'
```

`--debug` output:

```
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
/usr/bin/python
Darwin 15.6.0

<Environment {
    "colors": 256,
    "config": {
        "__meta__": {
            "about": "u'HTTPie configuration file'",
            "help": "u'https://httpie.org/docs#config'",
            "httpie": "u'0.9.9'"
        },
        "default_options": "[]"
    },
    "config_dir": "/Users/josh/.httpie",
    "is_windows": false,
    "stderr": "<open file '<stderr>', mode 'w' at 0x10f9fa1e0>",
    "stderr_isatty": true,
    "stdin": "<open file '<stdin>', mode 'r' at 0x10f9fa0c0>",
    "stdin_encoding": "UTF-8",
    "stdin_isatty": true,
    "stdout": "<open file '<stdout>', mode 'w' at 0x10f9fa150>",
    "stdout_encoding": "UTF-8",
    "stdout_isatty": true
}>

>>> requests.request(**{
    "allow_redirects": false,
    "auth": "None",
    "cert": "None",
    "data": {},
    "files": {},
    "headers": {
        "User-Agent": "HTTPie/0.9.9"
    },
    "method": "get",
    "params": {},
    "proxies": {},
    "stream": true,
    "timeout": 30,
    "url": "u'https://www.google.com'",
    "verify": true
})


http: error: AttributeError: 'X509' object has no attribute '_x509'
```

**Comment by sigmavirus24** [comment]
You need to upgrade/reinstall PyOpenSSL and Cryptography.

**Comment by joshkehn** [comment]
@sigmavirus24 Looks like this is an issue with how PyOpenSSL is installed for OS X machines with SIP. I typically install “global” packages with `pip install --user`, e.g.

```
pip install --upgrade PyOpenSSL Cryptography
[...]
Successfully installed Cryptography-1.7.1 PyOpenSSL-16.2.0 cffi-1.9.1 idna-2.2 pycparser-2.17 setuptools-32.2.0 six-1.10.0
```

And it has the same error. However, if I activate a virtualenv and reinstall httpie along with specific `--upgrade` for PyOpenSSL, and Cryptography, it works. Just installing httpie into a virtualenv doesn't make the correct version of PyOpenSSL available.

**Comment by joshkehn** [comment]
Going to close this issue for now, hopefully if someone else encounters this issue it gives them a path to resolve it.
