### ISSUE TITLE
Connection aborted: Bad StatusLine

### ISSUE THREAD

**Issue by afm-sayem** [jkbrzt/httpie#556]
If the query string contains `colon (:)` then I get an error in the console.:
`http: error: ConnectionError: ('Connection aborted.', Bad StatusLine("''",))`

Escaping didn't work. I tried escaping colon with backslash but got the same error.

Query: `http --debug :3000/games where[id:gt]:=2`
```
HTTPie 0.9.2
HTTPie data: /home/kishan/.httpie
Requests 2.9.1
Pygments 2.1
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] linux2

>>> requests.request({'allow_redirects': False,
 'auth': None,
 'cert': None,
 'data': OrderedDict(),
 'files': DataDict(),
 'headers': {'User-Agent': 'HTTPie/0.9.2', u'where[id': 'gt]:=2'},
 'method': 'get',
 'params': ParamsDict(),
 'proxies': {},
 'stream': True,
 'timeout': 30,
 'url': u'http://localhost:3000/games',
 'verify': True})

Traceback (most recent call last):
  File "/usr/bin/http", line 9, in <module>
    load_entry_point('httpie==0.9.2', 'console_scripts', 'http')()
  File "/usr/lib/python2.7/dist-packages/httpie/core.py", line 112, in main
    response = get_response(args, config_dir=env.config.directory)
  File "/usr/lib/python2.7/dist-packages/httpie/client.py", line 41, in get_response
    response = requests_session.request(**kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by sigmavirus24** [comment]
BadStatusLine means that httpie created a connection to the server, sent the request and the server gave a malformed response that httplib could not parse. If you look closely at the output from the debugging information you'll see:

```
 'headers': {'User-Agent': 'HTTPie/0.9.2', u'where[id': 'gt]:=2'},
```

It looks as though httpie splits on the `:` and sends a header that your server cannot parse. Perhaps httpie needs to `rsplit` instead of `split`.

**Comment by jkbrzt** [comment]
@afm-sayem it looks like an escaping issue. This works for me (Bash):

```bash
$ http --print=HB  httpbin.org/post 'where[id\:gt]:=2'
```
```http
POST /post HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 19
Content-Type: application/json
Host: httpbin.org
User-Agent: HTTPie/0.9.8

{
    "where[id:gt]": 2
}
```

**Comment by afm-sayem** [comment]
It worked after putting quotes around the querystring and escaping the colon.
