### ISSUE TITLE
Allow --verify=False and --verify=True (convert to no/yes) or raise warning on this bad input

### ISSUE THREAD

**Issue by hangtwenty** [jkbrzt/httpie#559]
I went down a rabbit hole trying to "fix" my OpenSSL and/or PyOpenSSL again, as I've had to deal with in the pass... only to realize the reason nobody else was seeing my issue is that it was completely my fault, bad usage. But maybe there is an enhancement opportunity here.

Compare these brief outputs (I will put `--debug` below):

```
$ http --verify=no "https://github.com" | head -n5


<!DOCTYPE html>
<html lang="en" class="">

$ http --verify=False "https://github.com" | head -n5

http: error: Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
```

I actually tried `--verify=False` first ... for some reason didn't try `--verify=no` until going through all sorts of other stuff. Maybe we can catch it and refuse to proceed, or at least print a warning about the likely error that will follow. Here's the full `--debug` output:

```
$ http --verify=False --debug "https://github.com"
HTTPie 0.9.9
Requests 2.13.0
Pygments 2.2.0
Python 2.7.12 (default, Oct 28 2016, 12:57:16)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
/usr/local/opt/python/bin/python2.7
Darwin 16.4.0

<Environment {
    "colors": 256,
    "config": {
        "__meta__": {
            "about": "u'HTTPie configuration file'",
            "help": "u'https://github.com/jkbrzt/httpie#config'",
            "httpie": "u'0.9.6'"
        },
        "default_options": "[]"
    },
    "config_dir": "/Users/mfloering/.httpie",
    "is_windows": false,
    "stderr": "<open file '<stderr>', mode 'w' at 0x10754d1e0>",
    "stderr_isatty": true,
    "stdin": "<open file '<stdin>', mode 'r' at 0x10754d0c0>",
    "stdin_encoding": "UTF-8",
    "stdin_isatty": true,
    "stdout": "<open file '<stdout>', mode 'w' at 0x10754d150>",
    "stdout_encoding": "UTF-8",
    "stdout_isatty": true
}>

>>> requests.request(**{
    "allow_redirects": false,
    "auth": "None",
    "cert": "None",
    "data": {},
    "files": {},
    "headers": {
        "User-Agent": "HTTPie/0.9.9"
    },
    "method": "get",
    "params": {},
    "proxies": {},
    "stream": true,
    "timeout": 30,
    "url": "u'https://github.com'",
    "verify": "u'False'"
})


http: error: Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
Traceback (most recent call last):
  File "/usr/local/bin/http", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/httpie/__main__.py", line 11, in main
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/httpie/core.py", line 227, in main
    log_error=log_error,
  File "/usr/local/lib/python2.7/site-packages/httpie/core.py", line 99, in program
    final_response = get_response(args, config_dir=env.config.directory)
  File "/usr/local/lib/python2.7/site-packages/httpie/client.py", line 70, in get_response
    response = requests_session.request(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 411, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 525, in load_verify_locations
    _raise_current_error()
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
```

If you look you can see that in a way this goes down to `requests`, not really HTTPie's fault --

```
$ python -c "import requests; print requests.get('https://github.com/', verify=False)"
/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
<Response [200]>

$ python -c "import requests; print requests.get('https://github.com/', verify=u'False')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 411, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 525, in load_verify_locations
    _raise_current_error()
  File "/usr/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]
```

However, I think in the case of just using `requests` code, the mistake in type casting is more obvious. Since HTTPie is a commandline tool and it's doing the initial argument handling, I think that would be the place to catch `True` or `False` strings and either automatically understand/cast them as needed, or at least throw a warning that these strings aren't going to do what you intend.

**Comment by hangtwenty** [comment]
I understand the issue is that `False` is being interpreted as `'False'` and an argument to a filepath... ([HTTPie CLI help explaining this](https://github.com/jkbrzt/httpie/blob/master/httpie/cli.py#L547), [`requests` documentation on this topic](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification)) ... again, understand this is a `requests` thing more than HTTPie thing ... still since HTTPie is all about providing a great interface, seems like we can do something pragmatic here.
